"use client"

import { AlertTriangle, Check, FileWarning, HelpCircle, Menu, X } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import type { KnowledgeReview } from "@/lib/types"

interface KnowledgeReviewProps {
  review: KnowledgeReview
  onResolveConflict: (id: string, action: string) => void
  onReviewProposal: (id: string, decision: "approved" | "rejected") => void
  onOpenMobileNavigation: () => void
}

export function KnowledgeReviewView(props: KnowledgeReviewProps) {
  const count = props.review.conflicts.length + props.review.proposals.length + props.review.unanswered_questions.length + props.review.failed_ingestions.length + props.review.reported_answers.length + props.review.low_quality_extractions.length
  return <section className="min-w-0 flex-1 overflow-y-auto bg-background"><header className="flex h-16 items-center gap-3 border-b px-3 sm:px-6"><Button variant="ghost" size="icon-lg" className="lg:hidden" aria-label="Open navigation" onClick={props.onOpenMobileNavigation}><Menu /></Button><h1 className="font-semibold">Knowledge Review</h1><Badge variant="secondary">{count} open</Badge></header><div className="mx-auto max-w-5xl px-4 py-8 sm:px-8"><div className="mb-7"><h2 className="text-2xl font-semibold tracking-tight">Keep company knowledge trustworthy</h2><p className="mt-1 text-sm text-muted-foreground">Resolve conflicts, approve chat-derived knowledge, and fill evidence gaps.</p></div><Tabs defaultValue="conflicts"><TabsList variant="line" className="max-w-full overflow-x-auto"><TabsTrigger value="conflicts">Conflicts ({props.review.conflicts.length})</TabsTrigger><TabsTrigger value="proposals">Proposals ({props.review.proposals.length})</TabsTrigger><TabsTrigger value="questions">Unanswered ({props.review.unanswered_questions.length})</TabsTrigger><TabsTrigger value="reported">Reported ({props.review.reported_answers.length})</TabsTrigger><TabsTrigger value="failed">Failed ({props.review.failed_ingestions.length})</TabsTrigger></TabsList>
    <TabsContent value="conflicts" className="space-y-3 pt-6">{props.review.conflicts.length ? props.review.conflicts.map((item) => <article key={item.id} className="rounded-xl border p-5"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 text-amber-600" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-medium">{item.conflict_type.replaceAll("_", " ")}</h3><Badge variant="outline">Needs review</Badge></div><p className="mt-1 text-sm text-muted-foreground">{item.summary}</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-lg bg-muted/50 p-3"><p className="text-xs font-medium text-muted-foreground">Existing source</p><p className="mt-1 text-sm">{item.left?.file_name ?? "Unavailable"} · v{item.left?.version}{item.left?.page ? ` · page ${item.left.page}` : ""}</p>{item.left?.excerpt ? <p className="mt-2 line-clamp-4 text-xs text-muted-foreground">{item.left.excerpt}</p> : null}</div><div className="rounded-lg bg-muted/50 p-3"><p className="text-xs font-medium text-muted-foreground">New source</p><p className="mt-1 text-sm">{item.right?.file_name ?? "Unavailable"} · v{item.right?.version}{item.right?.page ? ` · page ${item.right.page}` : ""}</p>{item.right?.excerpt ? <p className="mt-2 line-clamp-4 text-xs text-muted-foreground">{item.right.excerpt}</p> : null}</div></div><div className="mt-4 flex flex-wrap gap-2"><Button size="sm" onClick={() => props.onResolveConflict(item.id, "supersede")}>New supersedes old</Button><Button size="sm" variant="outline" onClick={() => props.onResolveConflict(item.id, "keep_both")}>Keep both</Button><Button size="sm" variant="ghost" onClick={() => props.onResolveConflict(item.id, "dismiss")}>Dismiss</Button></div></div></div></article>) : <Empty icon={<AlertTriangle />} text="No unresolved conflicts." />}</TabsContent>
    <TabsContent value="proposals" className="space-y-3 pt-6">{props.review.proposals.length ? props.review.proposals.map((item) => <article key={item.id} className="rounded-xl border p-5"><h3 className="font-medium">{item.title}</h3><p className="mt-2 line-clamp-4 whitespace-pre-wrap text-sm text-muted-foreground">{item.content}</p><div className="mt-4 flex gap-2"><Button size="sm" onClick={() => props.onReviewProposal(item.id, "approved")}><Check data-icon="inline-start" />Approve</Button><Button size="sm" variant="outline" onClick={() => props.onReviewProposal(item.id, "rejected")}><X data-icon="inline-start" />Reject</Button></div></article>) : <Empty icon={<Check />} text="No proposals awaiting approval." />}</TabsContent>
    <TabsContent value="questions" className="space-y-3 pt-6">{props.review.unanswered_questions.length ? props.review.unanswered_questions.map((item) => <article key={item.id} className="rounded-xl border p-5"><div className="flex gap-3"><HelpCircle className="text-primary" /><div><h3 className="font-medium">{item.question}</h3><p className="mt-1 text-xs text-muted-foreground">Reason: {item.reason.replaceAll("_", " ")}</p></div></div></article>) : <Empty icon={<HelpCircle />} text="No unanswered questions." />}</TabsContent>
    <TabsContent value="reported" className="space-y-3 pt-6">{props.review.reported_answers.length ? props.review.reported_answers.map((item) => <article key={item.id} className="rounded-xl border p-5"><div className="flex gap-3"><AlertTriangle className="text-amber-600" /><div><div className="flex items-center gap-2"><h3 className="font-medium">Answer reported as {item.rating}</h3><Badge variant="outline">Review</Badge></div><p className="mt-2 line-clamp-4 text-sm text-muted-foreground">{item.answer}</p>{item.note ? <p className="mt-2 text-sm">Reporter note: {item.note}</p> : null}</div></div></article>) : <Empty icon={<AlertTriangle />} text="No reported answers." />}</TabsContent>
    <TabsContent value="failed" className="space-y-3 pt-6">{props.review.failed_ingestions.map((item) => <article key={item.id} className="rounded-xl border p-5"><div className="flex gap-3"><FileWarning className="text-destructive" /><div><h3 className="font-medium">Extraction failed</h3><p className="mt-1 text-sm text-muted-foreground">{item.error || "Unknown extraction error"}</p></div></div></article>)}{props.review.low_quality_extractions.map((item) => <article key={item.version_id} className="rounded-xl border p-5"><div className="flex gap-3"><FileWarning className="text-amber-600" /><div><h3 className="font-medium">Visual verification required</h3><p className="mt-1 text-sm text-muted-foreground">{item.file_name} contains low-confidence visual evidence.</p></div></div></article>)}{!props.review.failed_ingestions.length && !props.review.low_quality_extractions.length ? <Empty icon={<FileWarning />} text="No failed or low-quality extractions." /> : null}</TabsContent>
  </Tabs></div></section>
}

function Empty({ icon, text }: { icon: React.ReactNode; text: string }) { return <div className="flex flex-col items-center rounded-xl border border-dashed p-10 text-center text-sm text-muted-foreground"><span className="mb-3">{icon}</span>{text}</div> }
